### ISSUE TITLE
Woking fail with Celery 4.3

### ISSUE THREAD

**Issue by endersonmenezes** [pmclanahan/django-celery-email#65]
I have traceback errors when using a Celery 4.3, any help for this?

**Comment by endersonmenezes** [comment]
```
Traceback (most recent call last):
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    try:
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/djcelery_email/tasks.py", line 58, in send_emails
    send_emails.retry([[message], combined_kwargs], exc=e, throw=False)
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/celery/app/task.py", line 703, in retry
    Returns:
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/djcelery_email/tasks.py", line 49, in send_emails
    sent = conn.send_messages([dict_to_email(message)])
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/home/enderson/Documentos/projetogrcunicesumar/venvdev/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Conexão recusada

```

**Comment by endersonmenezes** [comment]
Sorry, I'm Stupid. 
This errors is because my Celery.service is incorrect configs to receive a task.
